// Mocks generated by Mockito 5.4.6 from annotations
// in bolsa_empleo/test/presentation/auth/auth_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bolsa_empleo/core/services/api_service.dart' as _i2;
import 'package:bolsa_empleo/core/services/secure_storage_service.dart' as _i3;
import 'package:bolsa_empleo/data/models/user_tokens_model.dart' as _i4;
import 'package:bolsa_empleo/data/repositories/auth_repository.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecureStorageService_1 extends _i1.SmartFake
    implements _i3.SecureStorageService {
  _FakeSecureStorageService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserTokens_2 extends _i1.SmartFake implements _i4.UserTokens {
  _FakeUserTokens_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// clase con la que se simula [AuthRepository].
///
/// ver documentacion de mockito para mas informacion
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeApiService_0(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i2.ApiService);

  @override
  _i3.SecureStorageService get storageService =>
      (super.noSuchMethod(
            Invocation.getter(#storageService),
            returnValue: _FakeSecureStorageService_1(
              this,
              Invocation.getter(#storageService),
            ),
          )
          as _i3.SecureStorageService);

  @override
  _i6.Future<_i4.UserTokens> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i6.Future<_i4.UserTokens>.value(
              _FakeUserTokens_2(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i6.Future<_i4.UserTokens>);

  @override
  _i6.Future<_i4.UserTokens> register(
    String? email,
    String? password,
    String? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password, role]),
            returnValue: _i6.Future<_i4.UserTokens>.value(
              _FakeUserTokens_2(
                this,
                Invocation.method(#register, [email, password, role]),
              ),
            ),
          )
          as _i6.Future<_i4.UserTokens>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> getUserRole() =>
      (super.noSuchMethod(
            Invocation.method(#getUserRole, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);
}
